environments:
  default:
    values:
    - ../helmfile-values.yaml

---

repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - name: vpa
    namespace: newbie
    chart: fairwinds-stable/vpa
    version: "{{ .Values.Newbie.VPA.ChartVersion }}"
    # ref: https://github.com/FairwindsOps/charts/tree/master/stable/vpa
    values:
      - recommender:
          image:
            tag: "{{ .Values.Newbie.VPA.ImageTag }}"
      - updater:
          image:
              tag: "{{ .Values.Newbie.VPA.ImageTag }}"
      - admissionController:
          image:
              tag: "{{ .Values.Newbie.VPA.ImageTag }}"
