environments:
  default:
    values:
    - ../helmfile-values.yaml

---

repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - name: vpa
    namespace: newbie
    chart: fairwinds-stable/vpa
    version: "{{ .Values.Newbie.VPA.ChartVersion }}"
    # ref: https://github.com/FairwindsOps/charts/tree/master/stable/vpa
    values:
      # goldilocksはrecommenderのみ利用するため、updaterとadmissionControllerは無効化する
      # ref: https://github.com/FairwindsOps/goldilocks/blob/master/docs/installation.md#important-note-about-vpa
      # ref: https://github.com/FairwindsOps/charts/tree/master/stable/goldilocks#vpa-subchart
      - recommender:
          enabled: true
          image:
            tag: "{{ .Values.Newbie.VPA.Recommender.ImageTag }}"
      - updater:
          enabled: false
      - admissionController:
          enabled: false
