environments:
  default:
    values:
    - ../helmfile-values.yaml

---

repositories:
  - name: fairwinds-stable
    url: https://charts.fairwinds.com/stable

releases:
  - name: goldilocks
    namespace: newbie
    chart: fairwinds-stable/goldilocks
    version: "{{ .Values.Newbie.Goldilocks.ChartVersion }}"
    # ref: https://artifacthub.io/packages/helm/fairwinds-stable/goldilocks
    values: []
